### ISSUE TITLE
ebuilds for tlp incompatible with eudev

### ISSUE THREAD

**Issue by alexwilson** [dywisor/tlp-portage#1]
Gentoo by default includes eudev as opposed to udev, due to incompatabilities with systemd and in particular their direction for udev. udev is blocked by eudev, and so as such this package can no longer by installed on Gentoo systems. Please alter the ebuild to support eudev.

**Comment by dywisor** [comment]
=> Ebuild depends on virtual/udev now (beginning with version 0.3.7.1)
