### ISSUE TITLE
Gentoo/Funtoo >> /sys/module/snd_ac97_codec/parameters/power_save: Permission denied

### ISSUE THREAD

**Issue by gb00s** [dywisor/tlp-portage#11]
Even as root there is no chance to have access and create file & write value to /sys/module/snd_ac97_codec/parameters/power_save: Permission denied in Gentoo/Funtoo ... 

> tp ~ # rc-service tlp start
Applying power save settings.../usr/share/tlp/tlp-functions: line 1320: /sys/module/snd_ac97_codec/parameters/power_save: Permission denied
done.
Setting battery charge thresholds...done.

I made several attempts to change rights for this folder but failed.

**Comment by dywisor** [comment]
Your booted kernel doesn't allow you to control power save settings for snd_ac97_codec, this can't be fixed with chmod/chown.

Double-check that  ``CONFIG_SND_AC97_POWER_SAVE`` is enabled in your kernel config.

**Comment by gb00s** [comment]
Thank you. you are right. Solved it.
