### ISSUE TITLE
linux-x86-power-tools-3.17: location of XZ archive changed

### ISSUE THREAD

**Issue by stephanlukasczyk** [dywisor/tlp-portage#12]
The linux-3.17.tar.xz can no longer be found in http://www.kernel.org/pub/linux/kernel/v3.17/linux-3.17.tar.xz as the ebuild suggests, but is not located in https://www.kernel.org/pub/linux/kernel/v3.x/linux-3.17.tar.xz

This breaks the build of the package. A manual download of the tar-xz-archive and copying to `/usr/portage/distfiles` solves the issue in a hacky way.

Could you please update the ebuild of the linux-x86-power-tools package?

**Comment by dywisor** [comment]
Thanks for reporting, I've changed the `SRC_URI` accordingly.
