### ISSUE TITLE
dependency conflict over rfkill

### ISSUE THREAD

**Issue by rugubara** [dywisor/tlp-portage#13]
It seems that the util-linux-2.31 obsoletes rfkill. The ebuilds util-linux-2.31 and rfkill are conflicting. tlp-1.0 requires rfkill.

` * Error: The above package list contains packages which cannot be
 * installed at the same time on the same system.

  (net-wireless/rfkill-0.5-r3:0/0::gentoo, installed) pulled in by
    net-wireless/rfkill required by (app-laptop/tlp-1.0:0/0::tlp, installed)

  (sys-apps/util-linux-2.31:0/0::gentoo, ebuild scheduled for merge) pulled in by
    sys-apps/util-linux required by @system
    sys-apps/util-linux required by (x11-terms/gnome-terminal-3.24.2:0/0::gentoo, installed)
    >=sys-apps/util-linux-2.20.1-r2 required by (sys-fs/udisks-2.7.3:2/2::gentoo, installed)
    sys-apps/util-linux required by (app-text/build-docbook-catalog-1.21:0/0::gentoo, installed)
`

**Comment by rugubara** [comment]
`anton@r9-008cln ~/devel/rugubara/app-laptop/tlp $ diff -u /var/lib/layman/tlp/app-laptop/tlp/tlp-1.0.ebuild tlp-1.0-r0.ebuild
--- /var/lib/layman/tlp/app-laptop/tlp/tlp-1.0.ebuild   2017-06-06 10:54:32.332165133 +0300
+++ tlp-1.0-r0.ebuild   2017-10-25 15:13:52.596270958 +0300
@@ -55,14 +55,11 @@
 DEPEND=""
 RDEPEND="
        virtual/udev
-       sys-apps/util-linux
+        >=sys-apps/util-linux-2.31
        sys-apps/hdparm
        dev-lang/perl sys-apps/usbutils sys-apps/pciutils
        pm-utils?  ( sys-power/pm-utils )
        !pm-utils? ( sys-apps/systemd )
-       net-wireless/rfkill
-       || ( net-wireless/iw net-wireless/wireless-tools )
-       || ( sys-power/linux-x86-power-tools sys-apps/linux-misc-apps )

        rdw?                ( net-misc/networkmanager )
        tlp_suggests?       ( ${_OPTIONAL_RDEPEND} )
`

**Comment by rugubara** [comment]
[patch](https://pastebin.com/scd4v9cw)

**Comment by dywisor** [comment]
Thanks for reporting! ;)

Concerning the patch you've posted, it removes a bit too much from `RDEPEND`, like the dep on `iw`, so I've merged pr #14 instead.
