### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by lovesegfault** [dywisor/tlp-portage#18]
I wanted to send this note via email, but since I could not find @dywisor's email readily available I figured better to place it here than not at all.

I just wanted to take a moment to thank you for maintaining this so well, and for putting the time and effort to make this readily available on Gentoo. You've made my life easier and saved me a lot of time setting up my new laptop.

Thank you for being a maintainer!

**Comment by dywisor** [comment]
Thanks ;-)
