### ISSUE TITLE
Step n.2 in guide only applies for versions prior to 2.1.0

### ISSUE THREAD

**Issue by ghost** [dywisor/tlp-portage#22]
https://github.com/dywisor/tlp-portage/blob/maint/README.rst

This's not a technical issue in the build itself but simply adding `source /var/lib/layman/make.conf ` like mentioned in step n.2 will cause an error in make.conf and prevent from emerging in newer versions of layman

Since version 2.1.0, layman configuration is in /etc/portage/repos.conf and it's already set up correctly even tho the old config method's still supported it there's no such a file in newer versions

The error message:
> "/etc/portage/make.conf", line 38: /var/lib/layman/make.conf: No such file or directory

I admit that this's already mentioned in the linked wiki page but It would be nice to add "no need for this step since version 2.1.0"

Thank you for your contribution to open source

**Comment by dywisor** [comment]
Fixed, thanks.

Nowadays, the entire layman part (steps 1-3) could be replaced with a single ``repos.conf`` file. Might provide that as an option in future.

**Comment by dywisor** [comment]
Update: I've just added instructions for using ``repos.conf`` as an alternative to setting up layman to README.
