### ISSUE TITLE
Incorrect elogind system-sleep path on 17.1 profile

### ISSUE THREAD

**Issue by kitsunyan** [dywisor/tlp-portage#23]
Since 17.1 profile /lib and /lib64 are different dirs. On my system elogind wants system-sleep scripts to be placed to `/lib64/elogind/system-sleep`, but for tlp it's placed to `/lib/elogind/system-sleep` so `tlp-sleep` doesn't work.

**Comment by dywisor** [comment]
Thanks for reporting, I'll look into that.

**Comment by dywisor** [comment]
Should be fixed now, forgot to pass ``TLP_ELOD=...`` to ``make install``.
