### ISSUE TITLE
Please add TLPUI ebuild

### ISSUE THREAD

**Issue by joakim-tjernlund** [dywisor/tlp-portage#25]
https://github.com/d4nj1/TLPUI

**Comment by dywisor** [comment]
I do not participate in TLPUI development and could only host this in "pass-through" mode.

Haven't decided on this one yet, I'll keep it open for later.

**Comment by dywisor** [comment]
Closing as WONTFIX with the major reason being lack of faith: I don't see the need for a GUI tool to manage TLP's configuration and maintaining packages I don't care for seems like a bad idea in many ways.

Technically, this should be doable with the ``distutils-r1`` eclass, dependencies are listed in the README.
