### ISSUE TITLE
prepare for upcoming release 1.3.0

### ISSUE THREAD

**Issue by joakim-tjernlund** [dywisor/tlp-portage#26]
```
ebuild  tlp-9999-r2.ebuild clean compile
 * checking ebuild checksums ;-) ...                                                                                                                     [ ok ]
 * checking auxfile checksums ;-) ...                                                                                                                    [ ok ]
 * checking miscfile checksums ;-) ...                                                                                                                   [ ok ]
 * Determining the location of the kernel source code
 * Found kernel source directory:
 *     /usr/src/linux
 * Found sources for kernel version:
 *     4.19.97-x86_64
 * Checking for suitable kernel configuration options...                                                                                                 [ ok ]
>>> Unpacking source...
 * Repository id: linrunner_TLP.git
 * To override fetched repository properties, use:
 *   EGIT_OVERRIDE_REPO_LINRUNNER_TLP
 *   EGIT_OVERRIDE_BRANCH_LINRUNNER_TLP
 *   EGIT_OVERRIDE_COMMIT_LINRUNNER_TLP
 *   EGIT_OVERRIDE_COMMIT_DATE_LINRUNNER_TLP
 * 
 * Fetching https://github.com/linrunner/TLP.git ...
git fetch https://github.com/linrunner/TLP.git +refs/heads/master:refs/heads/master
git symbolic-ref refs/git-r3/app-laptop/tlp/0/__main__ refs/heads/master
 * Checking out https://github.com/linrunner/TLP.git to /var/tmp/portage/app-laptop/tlp-9999-r2/work/tlp-9999 ...
git checkout --quiet master
GIT update -->
   repository:               https://github.com/linrunner/TLP.git
   at the commit:            e51c52f8ab9690c5f71bb2d0e4b413d603df3785
 * Repository id: dywisor_tlp-gentoo-additions.git
 * To override fetched repository properties, use:
 *   EGIT_OVERRIDE_REPO_DYWISOR_TLP_GENTOO_ADDITIONS
 *   EGIT_OVERRIDE_BRANCH_DYWISOR_TLP_GENTOO_ADDITIONS
 *   EGIT_OVERRIDE_COMMIT_DYWISOR_TLP_GENTOO_ADDITIONS
 *   EGIT_OVERRIDE_COMMIT_DATE_DYWISOR_TLP_GENTOO_ADDITIONS
 * 
 * Fetching https://github.com/dywisor/tlp-gentoo-additions.git ...
git fetch https://github.com/dywisor/tlp-gentoo-additions.git +refs/heads/master:refs/heads/master
git symbolic-ref refs/git-r3/app-laptop/tlp/0/__main__ refs/heads/master
 * Checking out https://github.com/dywisor/tlp-gentoo-additions.git to /var/tmp/portage/app-laptop/tlp-9999-r2/work/gentoo-additions ...
git checkout --quiet master
GIT update -->
   repository:               https://github.com/dywisor/tlp-gentoo-additions.git
   at the commit:            830eb638cc2f4bd979ede04df4dc3824c3d8aec1
>>> Source unpacked in /var/tmp/portage/app-laptop/tlp-9999-r2/work
>>> Preparing source in /var/tmp/portage/app-laptop/tlp-9999-r2/work/tlp-9999 ...
make V=1 -C /var/tmp/portage/app-laptop/tlp-9999-r2/work/gentoo-additions TLP_SRC=/var/tmp/portage/app-laptop/tlp-9999-r2/work/tlp-9999 TLP_CONF=/etc/tlp.conf TLP_APPENDVER=+git-master-20200123 livepatch-base 
make: Entering directory '/var/tmp/portage/app-laptop/tlp-9999-r2/work/gentoo-additions'
test -n "/var/tmp/portage/app-laptop/tlp-9999-r2/work/tlp-9999"
{ set -e;  } </dev/null
{ set -e;  } </dev/null
{  true; } </dev/null;
touch /var/tmp/portage/app-laptop/tlp-9999-r2/work/tlp-9999/.lp_basepatch.stamp
test -n "/var/tmp/portage/app-laptop/tlp-9999-r2/work/tlp-9999"
bash /var/tmp/portage/app-laptop/tlp-9999-r2/work/gentoo-additions/bin/tlp-editsrc.bash -d "/var/tmp/portage/app-laptop/tlp-9999-r2/work/tlp-9999"  MACRO appendver +git-master-20200123 CFGVAR  TLP_ENABLE 0 MACRO   TLP_LOAD_MODULES MACRO   TLP_DEBUG _ MACRO   pcilist-sbin
sed: can't read ./default: No such file or directory
died: command 'tlp_src_apply_edit_expressions_to ./default' returned 2
make: *** [Makefile:121: /var/tmp/portage/app-laptop/tlp-9999-r2/work/tlp-9999/.lp_base.stamp] Error 2
make: Leaving directory '/var/tmp/portage/app-laptop/tlp-9999-r2/work/gentoo-additions'
 * ERROR: app-laptop/tlp-9999-r2::transmode failed (prepare phase):
 *   emake failed

**Comment by dywisor** [comment]
* `9999` is out of sync
* probably broken since configuration file handling has changed upstream
* ETA of fixed ebuild (``tlp-9999-r3``): 2020-01-27
* for the time being, stick to the release version, ``tlp-1.2.2-r1``
---

``tlp-9999-r2`` expects a ``1.2.x``-ish upstream source tree.
Versions <= ``1.2.x`` build against two git repos, ``TLP`` and ``tlp-gentoo-additions``.
Versions >= ``1.3.x`` (which is currently in beta) will no longer need the extra ``tlp-gentoo-additions`` repo.
I have proposed the necessary changes upstream earlier this week and they already got merged, writing the updated ebuild remains to be done.

**Comment by dywisor** [comment]
@joakim-tjernlund, all,

``app-laptop/tlp-9999-r3``, ``app-laptop/tlp-1.3.0_beta4`` added to the repo, commit 8f790f5b84c517573ee964ac899ee4564e7cf201:

> Prepare for the next release:
>
> - TODO: README
>
> - configuration file handling has changed:
>   - baseline provided by package in /usr/share/tlp/defaults.conf
>   - drop-in conf snippets read from /etc/tlp.d/*.conf
>   - overrides read from /etc/tlp.conf
>
>   Users should review their /etc/tlp.conf after upgrading.
>   Default values should no longer be set in that file,
>   only deviations thereof.
>
>   Gentoo-specific customizations such as disabling TLP by default
>   now reside in /etc/tlp.d/01-gentoo.conf.
>   To enable TLP, set 'TLP_ENABLE=1' in /etc/tlp.conf
>   (or any file in /etc/tlp.d/ that gets read after 01-gentoo.conf,
>   e.g. 05-enable.conf).
>
> - tlp_suggests USE flag renamed to tlp-suggests,
>   underscore is reserved as reported by pkgcheck
>
> - x86_energy_perf_policy is an optional dep now,
>   not necessarily needed on kernel versions >= 5.2

Optional dependencies are pulled in by default now (sill controllable via the ``tlp-suggests`` USE flag).

Builds and installs fine in LXC and tlp-stat output looks OK, but haven't tested on real hardware yet.

If anybody wants to give it a spin, make sure to review your ``/etc/tlp.conf`` after installing and report back success/failure here.

You may also contribute to the beta test, linrunner/TLP#449. Please do not report Gentoo-related issues there - if unsure, post them here.

**Comment by dywisor** [comment]
done - README updated

**Comment by joakim-tjernlund** [comment]
Noticed  the /etc/tlp.d/01-gentoo.conf: TLP_ENABLE=0

I find it odd that the default is disabled here. One has to do 3 things to get TLP going:
emerge tlp, then edit/add a TLP_ENABLE=1 conf snippet, run the service
IMHO a user who installs and runs the service find it odd that he in addition has to edit
a config file too.

**Comment by dywisor** [comment]
Moved to a separate issue #27 as that is not specifically related to the ``1.3`` release.
