### ISSUE TITLE
move /etc/conf.d/tlp to /etc/tlp

### ISSUE THREAD

**Issue by zhou13** [dywisor/tlp-portage#4]
Hi, I'm a systemd user and I find that the position of the configuration file makes me quite uncomfortable.  `/etc/conf.d` is mainly used for OpenRC.  For package such as tlp that supports both init and systemd, I think it is better to put the configuration file under `/etc` directly

**Comment by dywisor** [comment]
Sensible suggestion. What about `/etc/tlp.conf` - many files in /etc end with `.conf` or `.rc`?

**Comment by zhou13** [comment]
I think `/etc/tlp.conf` is fine.

**Comment by dywisor** [comment]
Changed in 0.5-r1. Masked because there's no "upgrade path" so far (move /etc/conf.d/tlp -> /etc/tlp.conf) and the final config file location needs to be coordinated with upstream.

**Comment by linrunner** [comment]
Upstream (me) would like to stick with **/etc/default/tlp**.

It's not the best solution but historically established in all distros except gentoo, in the official docs and last but not least in myriad blogs around the www. Imho it's just to much hassle to change it for very little benefit (if any).

**Comment by dywisor** [comment]
OK, just wanted to ensure that there won't be any /etc/tlp.conf <-> /etc/tlp confusion.

@zhou13, reopen if there are any issues with the ebuild
