### ISSUE TITLE
CONFIG_ACPI_PROC_EVENT no longer in kernel

### ISSUE THREAD

**Issue by ghost** [dywisor/tlp-portage#5]
The README recommends that CONFIG_ACPI_PROC_EVENT is enabled in the kernel configuration,
but it seems to have been replaced by CONFIG_ACPI_PROCFS and CONFIG_ACPI_PROCFS_POWER. (linux 3.14.17)

Should these be enabled instead or are they deprecated for tlp as well?

**Comment by dywisor** [comment]
As of TLP 0.5, `ACPI_PROC_EVENT` is "optional". It _is_ required for `thinkpad-radiosw`'s acpi rule, which handles the hardware rfkill switch event on ThinkPads - `DEVICES_TO_ENABLE_ON_RADIOSW` in the config file, disabled by default anyway. acpid doesn't get the event without `ACPI_PROC_EVENT=y`, enabling `ACPI_PROCFS{,_POWER}` won't help.

So the general recommendation is:
- enable `ACPI_PROC_EVENT` if you have a Thinkpad and an older kernel (e.g. 3.10)
- don't care and ignore the warning produced by the ebuild on linux >= 3.12, losing `thinkpad-radiosw`

I'll update the README accordingly.

**Comment by fancywriter** [comment]
CONFIG_PM_RUNTIME is also no longer in kernel (I am using gentoo-sources-4.6.2), I think it is kind of always included and can't be configured anymore.

**Comment by dywisor** [comment]
Hi,

thanks for the pointer. It's a documentation issue, the ebuilds check for `PM` and not `PM_RUNTIME`. I'll update the readme.

**Comment by fancywriter** [comment]
@dywisor looks like issue #5 can be closed, right?.. I see no big issue here or anything to improve right now - README is updated.
