### ISSUE TITLE
0.6 has no OpenRC script

### ISSUE THREAD

**Issue by dbordak** [dywisor/tlp-portage#6]
I'm not sure if the removal is intentional or not (looks like it is?) but the Readme instructs OpenRC users to use a script that is no longer installed as of 0.6. Is this necessary anymore? If not, could you update the Readme?

**Comment by dywisor** [comment]
ouch, I've moved the file to this repo (beginning with ~~0.5-r2~~ 0.6), but forgot to install it in src_install().
Will be fixed ASAP.

Thanks for reporting! ;)
